apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.12
    helm:
      releaseName: grafana
      parameters:
        - name: service.type
          value: ClusterIP
        - name: adminUser
          value: admin
        - name: adminPassword
          value: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: {}
