apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.6.2
    helm:
      valuesObject:
        image:
          repository: bitnami/mlflow
          tag: 2.10.1

        backendStore:
          postgres:
            enabled: true
            host: postgres-postgresql.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflowpass

        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            awsAccessKeyId: minio
            awsSecretAccessKey: minio123

        service:
          type: ClusterIP
          port: 5000

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
          AWS_ACCESS_KEY_ID: minio
          AWS_SECRET_ACCESS_KEY: minio123
          AWS_REGION: us-east-1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
