apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.8.0
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: false

        pushgateway:
          enabled: false

        kubeStateMetrics:
          enabled: false

        nodeExporter:
          enabled: false

        server:
          service:
            type: ClusterIP
          persistentVolume:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: {}
