apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-stack
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/verity1886/argocd-apps.git
    targetRevision: HEAD
    path: applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
